###get all localities
GET http://localhost:3000/api/localities

###get a locality by id
GET http://localhost:3000/api/localities/6

###create a new locality
POST http://localhost:3000/api/localities
Content-Type: application/json

{
  "id": "7",
  "name": "San Pedro"
}

###update an existing locality
PUT http://localhost:3000/api/localities/7
Content-Type: application/json

{
  "name": "San Nicolas"
}

###delete a locality
DELETE http://localhost:3000/api/localities/7