###get all drivers
GET http://localhost:3000/api/drivers

###get inactive drivers
GET http://localhost:3000/api/drivers/inactive

###get a driver by id
GET http://localhost:3000/api/drivers/1

###create a new driver
POST http://localhost:3000/api/drivers
Content-Type: application/json

{
  "dni": "40123456",
  "firstName": "Roberto",
  "lastName": "Vega",
  "phone": "6667778889"
}

###reactivate a driver
POST http://localhost:3000/api/drivers/1/reactivate

###update an existing driver
PUT http://localhost:3000/api/drivers/1
Content-Type: application/json

{
  "firstName": "Roberto",
  "lastName": "Vega",
  "phone": "6667778889"
}

###delete a driver
DELETE http://localhost:3000/api/drivers/1
