###obtener todos los clientes
GET http://localhost:3000/api/clientes

###obtener un cliente por id
GET http://localhost:3000/api/clientes/4

###crear un nuevo cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "id": "6",
  "nombre": "Juan",
  "apellido": "Lopez",
  "email": "juan.lopez@example.com",
  "telefono": "9999999999"
}

###actualizar un cliente existente
PUT http://localhost:3000/api/clientes/6
Content-Type: application/json

{

  "nombre": "Julio",
  "apellido": "Perez",
  "email": "julio.perez@example.com",
  "telefono": "9999999999"
}
### Modificar solo el nombre de un cliente existente
PATCH http://localhost:3000/api/clientes/6
Content-Type: application/json

{

  "nombre": "Carlos",
  "email": "carlos.perez@example.com"
}

###eliminar un cliente
DELETE http://localhost:3000/api/clientes/6